#!/bin/bash
#
# See skript otsib var kataloogis .log lõpuga faile ning väljastab neid kahanevas järjekorras ning väljastab ka mitu rida on
#
find /var -type f -name "*.log" 2>/dev/null -exec wc -l {}  \; | sort -n -r
#
#

