#!/bin/bash
#
#
#
read -p "Kolmnurga küje A pikkus: " A
read -p "Kolmurga külje B pikkus: " B

ruutc=$(bc <<< "$A * $A + $B * $B")

echo "Hüpotenuusi ruut on $ruutc cm"

C=$(bc <<< "scale=2; sqrt ( $ruutc )")

echo "Hüpotenuusi pikkus on $C cm"
