#!/bin/bash
#
#skript arvutab, millal inimele reisilt tagasi jõud
echo ""
echo "Esmaspäev-1 Teisipäev-2 Kolmapäev-3 Neljapäev-4 Reede-5 Laupäev-6 Pühapäev-7"
echo ""
echo "Sisesta number, mis päeval te lahkute: "
#
read lahkumine
#
echo "Sisesta ööpäevade arv: "
#
read reisipikkus
#
FF=$(($reisipikkus % 7))
tagasitulek=$(($lahkumine + $FF))
echo ""
echo "Tagasi jõuate päeval number:"$tagasitulek

